version: '3.3'
services:
  graphql-api:
    container_name: rest-grahpql-api
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 4001:4001
    external_links:
      - db
    depends_on:
      - db
  db:
    container_name: 'pg-restaurant'
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
volumes:
  database: